/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnvBench: typeof import('./src/components/envBench.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Workbench: typeof import('./src/components/workbench.vue')['default']
    WorkbenchContent: typeof import('./src/components/workbenchSpace/workbenchContent.vue')['default']
    WorkbenchRequest: typeof import('./src/components/workbenchSpace/workbenchRequest.vue')['default']
    WorkbenchResponse: typeof import('./src/components/workbenchSpace/workbenchResponse.vue')['default']
    WorkbenchSendApi: typeof import('./src/components/workbenchSpace/workbenchSendApi.vue')['default']
    WorkbenchSpace: typeof import('./src/components/workbenchSpace/index.vue')['default']
    WorkbenchTabs: typeof import('./src/components/workbenchSpace/workbenchTabs.vue')['default']
    Workbox: typeof import('./src/components/workbox.vue')['default']
    Workflow: typeof import('./src/components/workflow.vue')['default']
    WorkflowConnectSql: typeof import('./src/components/workflowSpace/workflowConnectSql.vue')['default']
    WorkflowHttp: typeof import('./src/components/workflowSpace/workflowHttp.vue')['default']
    WorkflowSleep: typeof import('./src/components/workflowSpace/workflowSleep.vue')['default']
    WorkflowSpace: typeof import('./src/components/workflowSpace/index.vue')['default']
    WorkflowSql: typeof import('./src/components/workflowSpace/workflowSql.vue')['default']
    WorkflowTabs: typeof import('./src/components/workflowSpace/workflowTabs.vue')['default']
  }
}
